FROM node:16-alpine

RUN mkdir -p /home/node/app
WORKDIR '/home/node/app'


COPY --chown=node:node ./package.json ./
RUN npm install

RUN chown -R node:node /home/node/app/node_modules

COPY --chown=node:node ./ ./

CMD ["npm", "run", "start"]